name: HiberniaDiscord
version: ${project.version}
main: io.paradaux.hiberniadiscord.bukkit.HiberniaDiscord
api-version: 1.16
description: HiberniaDiscord's Bukkit Functioanlity
commands:
  disable:
    usage: /disable